// Statice Routes

GET http://localhost:5237/

###

GET http://localhost:5237/Downloads

###

PUT http://localhost:5237/

###

DELETE http://localhost:5237/

###

POST http://localhost:5237/

// Routes with parameters (Dynamic Routes)

###

GET http://localhost:5237/Users/4

###

GET http://localhost:5237/Users/23

###

GET http://localhost:5237/Names/ABC

###
GET http://localhost:5237/Products/55

###
GET http://localhost:5237/Products/



